---
- name: Create the /var/cisa/example directory
  file:
    path: /var/cisa/example
    state: directory
    mode: 0755

- name: Copy some necessary files
  copy:
    src: "{{ item }}"
    dest: "/var/cisa/example/{{ item }}"
    mode: 0744
  loop:
    - docker-compose.yml
    - quote.txt
  notify:
    - Start docker composition
